### ISSUE TITLE
Move local crate dependencies to root Cargo.toml

### ISSUE THREAD

**Issue by lazovicff** [openrankprotocol/openrank#102]
Consider factoring these into the workspace Cargo.toml, i.e. in there:
```toml
openrank-sequencer = { path = "sequencer", version = "0.1.0" }
openrank-common = { path = "common", version = "0.1.0" }
openrank-smart-contract-client = { path = "smart-contract-client", version = "0.1.0" }
```
And use them from here:
```toml
openrank-sequencer = { workspace = true }
openrank-common = { workspace = true }
openrank-smart-contract-client = { workspace = true }
```
